name: CI

env:
    CONFIGURATION: Release

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
        include-prerelease: true

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration $Env:CONFIGURATION

    - name: Test
      run: dotnet test --no-build --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

    - name: Codecov
      uses: codecov/codecov-action@v4
