name: Deploy

env:
    CONFIG: Release
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    OUTPUT: ShaclService/published
    PROFILE: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
        include-prerelease: true

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration ${{ env.CONFIG }}

    - name: Test
      run: dotnet test --no-build --configuration ${{ env.CONFIG }} --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

    - name: Codecov
      uses: codecov/codecov-action@v5

    - name: Publish
      run: dotnet publish ShaclService --no-build --configuration ${{ env.CONFIG }} --output ${{ env.OUTPUT }}

    - name: Deploy
      uses: azure/webapps-deploy@v3
      with:
          app-name: shacl
          slot-name: Production
          publish-profile: ${{ env.PROFILE }}
          package: ${{ env.OUTPUT }}
